name: PR-CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Package Retail
        uses: BigWigsMods/packager@master
        with:
            args: -g retail -d

      - name: Package Classic
        uses: BigWigsMods/packager@master
        with:
            args: -g classic -d

      - name: Package BC Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc -d

      - name: Package Wrath Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath -d
  
      - name: Package Cata Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g cata -d

      - uses: actions/upload-artifact@v4
        with:
          name: Baggins
          path: /*.zip

